name: Reddit Emoji Test Checks

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    env:
      ORG: uazhlt
      IMAGE_NAME: ling-508-pa-week5
      TAG: latest
    runs-on: ubuntu-latest
    
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=10s --health-retries=10
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build the docker image
        run: |
          docker build . --file Dockerfile --tag ${ORG}/${IMAGE_NAME}:${TAG}
      - name: Build database
        run: |
          docker run -i --network ${{ job.services.mysql.network }} ${ORG}/${IMAGE_NAME}:${TAG} python /db/init_database.py
      - name: Run the tests
        run: |
          docker run -i --network ${{ job.services.mysql.network }} ${ORG}/${IMAGE_NAME}:${TAG} python -m pytest tests
