name: Reddit Emoji Test Checks

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    env:
      ORG: "uazhlt"
      IMAGE_NAME: "ling-508-pa-week6"
      TAG: "latest"
    runs-on: ubuntu-latest
    
    services:
      db:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=10s --health-retries=10
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_USER_AGENT: "comment-scrape"
          envkey_CLIENT_ID: "${{ secrets.CLIENT_ID }}"
          envkey_CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          directory: ""
          file_name: .env
          fail_on_empty: false
      - name: Build the docker image
        run: |
          docker build . --file Dockerfile --tag ${ORG}/${IMAGE_NAME}:${TAG}
      - name: Run the tests
        run: |
          docker run -i --network ${{ job.services.mysql.network }} ${ORG}/${IMAGE_NAME}:${TAG} python -m pytest tests
